---
AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Container Repository (ECR)

Parameters:

  RepositoryName:
    Type: String
    Description: Leave empty to use stack name
    Default: ""

Conditions:
  UseStackName: !Equals [!Ref RepositoryName, ""]

Resources:

  Repository: 
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties: 
      RepositoryName: !If
        - UseStackName
        - !Ref AWS::StackName
        - !Ref RepositoryName
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
Outputs:

  RepositoryArn:
    Description: ECR ARN
    Value: !GetAtt Repository.Arn
